---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  product_name: chef
  product_version: 14.1.12
  install_strategy: always

verifier:
  name: inspec

platforms:
  - name: win2016gui-virtualbox
    driver:
      customize:
        memory: 2048
        cpus: 2

suites:
  - name: default
    run_list:
      - recipe[win_time::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
