AccessorMethodName:
  Enabled: false
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4.1
LineLength:
  Max: 120 # Default is 80
Metrics/BlockLength:
  Max: 50 # Default is 40
Metrics/ModuleLength:
  Enabled: false
RedundantReturn:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/WordArray:
  EnforcedStyle: brackets
